### ISSUE TITLE
Reading altitude info

### ISSUE THREAD

**Issue by mostafaibrahim** [Seeed-Studio/Seeed_Wio_GPS_Board#4]
How can the code be modified to get the altitude info?

**Comment by Kyle-Roth** [comment]
lol, I don't actaully use github often. I will have to check this issues forum more often.
There is an array called y(this is in the MainWindow class) that contains altitude data. And you can take that altitude and add ele0 (reference elevation at landing point) to get elevation if you'd perfer.
